import test from 'node:test'; import assert from 'node:assert/strict'; import activate, { bridgePing } from './index.js';
function api(){const commands:any={}; return {commands, registerCommand:(name:string,opts:any)=>{commands[name]=opts; assert.equal(typeof opts.handler,'function');}};}
test('registers Villani Pi commands',()=>{const a=api(); activate(a); assert.deepEqual(Object.keys(a.commands),['villani','villani-abort','villani-confirm-test','villani-ping','villani-doctor','villani-proxy-test','villani-bridge-ping']);});
test('/villani-ping only notifies OK',async()=>{const a=api(); activate(a); const notes:any[]=[]; await a.commands['villani-ping'].handler('',{ui:{notify:(m:string)=>notes.push(m)}}); assert.deepEqual(notes,['Villani ping OK']);});
test('/villani-confirm-test accepted, rejected, and missing UI are visible',async()=>{for(const value of [true,false]){const a=api(); activate(a); const notes:string[]=[]; await a.commands['villani-confirm-test'].handler('',{ui:{notify:(m:string)=>notes.push(m),confirm:async()=>value}}); assert.equal(notes[0],'Villani confirmation test starting...'); assert.equal(notes.at(-1),value?'Villani confirmation accepted':'Villani confirmation rejected');} const a=api(); activate(a); const notes:string[]=[]; await a.commands['villani-confirm-test'].handler('',{ui:{notify:(m:string)=>notes.push(m)}}); assert.deepEqual(notes,['Villani confirmation test starting...','Villani confirmation UI unavailable']);});
test('/villani-doctor prints diagnostics without secrets',async()=>{const a=api(); activate(a); const notes:string[]=[]; process.env.VILLANI_API_KEY='secret'; try{await a.commands['villani-doctor'].handler('',{cwd:'/tmp/repo',model:{id:'m'},modelRegistry:{getApiKeyAndHeaders(){}} ,ui:{notify:(m:string)=>notes.push(m)}}); const msg=notes.join('\n'); assert.match(msg,/package version: 0.1.4/); assert.match(msg,/runtime version: 0.1.3/); assert.match(msg,/ctx.model exists: true/); assert.doesNotMatch(msg,/secret|VILLANI_API_KEY/);} finally{delete process.env.VILLANI_API_KEY;}});
import { chmodSync, existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { runVillani } from './index.js';
function bridgeScript(body:string){const d=mkdtempSync(join(tmpdir(),'pi-villani-run-')); const p=join(d,'bridge.mjs'); writeFileSync(p,`#!/usr/bin/env node\n${body}`); chmodSync(p,0o755); return p;}
const readyPrelude="process.stdout.write(JSON.stringify({type:'ready'})+'\\n');\nconst send=e=>process.stdout.write(JSON.stringify(e)+'\\n');\n";


test('/villani sends command notification and only reports run started after run_started event',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping'){send({type:'pong'}); continue;} send({type:'run_started',id:msg.id}); send({type:'phase',id:msg.id,name:'x'}); send({type:'run_completed',id:msg.id,summary:'done'});}}); setTimeout(()=>{},500);\n"); process.env.VILLANI_COMMAND=p; const notes:string[]=[]; try{process.env.VILLANI_USE_PI_MODEL='false'; await runVillani('task',{sendMessage:(m:string)=>notes.push(m)},{ui:{notify:(m:string)=>notes.push(m)},cwd:'/tmp',model:{id:'m'},});} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; delete process.env.VILLANI_USE_PI_MODEL;} const joined=notes.join('\n'); assert.match(joined,/Villani bridge ready/); assert.match(joined,/Villani run command sent/); assert.match(joined,/Villani run started\./); assert.ok(notes.indexOf('Villani run command sent.')<notes.indexOf('Villani run started.'));});

test('/villani missing run_started timeout reports visible error instead of started',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping')send({type:'pong'});}}); console.error('no ack'); setTimeout(()=>{},15000);\n"); process.env.VILLANI_COMMAND=p; const notes:string[]=[]; try{process.env.VILLANI_USE_PI_MODEL='false'; await assert.rejects(()=>runVillani('task',{},{ui:{notify:(m:string)=>notes.push(m)},cwd:'/tmp'}),/did not acknowledge run command within 10 seconds.*no ack/s);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; delete process.env.VILLANI_USE_PI_MODEL;} assert.doesNotMatch(notes.join('\n'),/Villani run started\./);});


async function waitForPidGone(pid:number,timeoutMs=3000){const deadline=Date.now()+timeoutMs; while(Date.now()<deadline){try{process.kill(pid,0);}catch{return;} await new Promise(r=>setTimeout(r,50));} assert.fail(`fake bridge process ${pid} remained alive`);}

test('/villani run_started timeout cleans up fake bridge process',async()=>{const oldCommand=process.env.VILLANI_COMMAND; const oldUsePi=process.env.VILLANI_USE_PI_MODEL; const d=mkdtempSync(join(tmpdir(),'pi-villani-cleanup-')); const pidFile=join(d,'pid'); const p=join(d,'bridge.mjs'); writeFileSync(p,`#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
writeFileSync(${JSON.stringify(pidFile)},String(process.pid));
process.stdout.write(JSON.stringify({type:'ready'})+'\\n');
process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping')process.stdout.write(JSON.stringify({type:'pong'})+'\\n');}});
console.error('cleanup no ack');
setInterval(()=>{},1000);
`); chmodSync(p,0o755); process.env.VILLANI_COMMAND=p; process.env.VILLANI_USE_PI_MODEL='false'; const notes:string[]=[]; try{await assert.rejects(()=>runVillani('task',{},{ui:{notify:(m:string)=>notes.push(m)},cwd:'/tmp'}),/did not acknowledge run command within 10 seconds.*cleanup no ack/s); assert.ok(existsSync(pidFile)); await waitForPidGone(Number(readFileSync(pidFile,'utf8'))); assert.doesNotMatch(notes.join('\n'),/Villani run started\./);} finally{if(oldCommand===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=oldCommand; if(oldUsePi===undefined) delete process.env.VILLANI_USE_PI_MODEL; else process.env.VILLANI_USE_PI_MODEL=oldUsePi;}});


test('bridge exit before ready with ModuleNotFoundError produces pip install diagnostic',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript("console.error(\"ModuleNotFoundError: No module named 'villani_code'\"); process.exit(1);\n"); process.env.VILLANI_COMMAND=p; try{await assert.rejects(()=>bridgePing({ui:{notify:()=>{}}}),/pip install -e/);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old;} });

test('/villani-bridge-ping succeeds with fake bridge',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split(/\\n/)){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping')send({type:'pong'});}}); setTimeout(()=>{},500);\n"); process.env.VILLANI_COMMAND=p; const notes:string[]=[]; try{await bridgePing({ui:{notify:(m:string)=>notes.push(m)}});} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old;} assert.match(notes.join('\n'),/Villani bridge ping succeeded/);});

test('/villani-bridge-ping surfaces stderr on failure',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript("console.error('boom stderr'); process.exit(2);\n"); process.env.VILLANI_COMMAND=p; try{await assert.rejects(()=>bridgePing({ui:{notify:()=>{}}}),/boom stderr/);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old;} });
