import test from 'node:test'; import assert from 'node:assert/strict'; import activate, { bridgePing } from './index.js';
function api(){const commands:any={}; return {commands, registerCommand:(name:string,opts:any)=>{commands[name]=opts; assert.equal(typeof opts.handler,'function');}};}
test('registers Villani Pi commands',()=>{const a=api(); activate(a); assert.deepEqual(Object.keys(a.commands),['villani','villani-abort','villani-confirm-test','villani-ping','villani-doctor','villani-proxy-test','villani-bridge-ping']);});
test('/villani-ping only notifies OK',async()=>{const a=api(); activate(a); const notes:any[]=[]; await a.commands['villani-ping'].handler('',{ui:{notify:(m:string)=>notes.push(m)}}); assert.deepEqual(notes,['Villani ping OK']);});
test('/villani-confirm-test accepted, rejected, and missing UI are visible',async()=>{for(const value of [true,false]){const a=api(); activate(a); const notes:string[]=[]; await a.commands['villani-confirm-test'].handler('',{ui:{notify:(m:string)=>notes.push(m),confirm:async()=>value}}); assert.equal(notes[0],'Villani confirmation test starting...'); assert.equal(notes.at(-1),value?'Villani confirmation accepted':'Villani confirmation rejected');} const a=api(); activate(a); const notes:string[]=[]; await a.commands['villani-confirm-test'].handler('',{ui:{notify:(m:string)=>notes.push(m)}}); assert.deepEqual(notes,['Villani confirmation test starting...','Villani confirmation UI unavailable']);});
test('/villani-doctor prints diagnostics without secrets',async()=>{const a=api(); activate(a); const notes:string[]=[]; process.env.VILLANI_API_KEY='secret'; try{await a.commands['villani-doctor'].handler('',{cwd:'/tmp/repo',model:{id:'m'},modelRegistry:{getApiKeyAndHeaders(){}} ,ui:{notify:(m:string)=>notes.push(m)}}); const msg=notes.join('\n'); assert.match(msg,/package version: 0.1.4/); assert.match(msg,/runtime version: 0.1.3/); assert.match(msg,/ctx.model exists: true/); assert.doesNotMatch(msg,/secret|VILLANI_API_KEY/);} finally{delete process.env.VILLANI_API_KEY;}});
import { chmodSync, existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { runVillani } from './index.js';
function bridgeScript(body:string){const d=mkdtempSync(join(tmpdir(),'pi-villani-run-')); const p=join(d,'bridge.mjs'); writeFileSync(p,`#!/usr/bin/env node\n${body}`); chmodSync(p,0o755); return p;}
const readyPrelude="process.stdout.write(JSON.stringify({type:'ready'})+'\\n');\nconst send=e=>process.stdout.write(JSON.stringify(e)+'\\n');\n";


test('/villani sends command notification and only reports run started after run_started event',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping'){send({type:'pong'}); continue;} send({type:'run_started',id:msg.id}); send({type:'phase',id:msg.id,name:'x'}); send({type:'run_completed',id:msg.id,summary:'done'});}}); setTimeout(()=>{},500);\n"); process.env.VILLANI_COMMAND=p; const notes:string[]=[]; try{process.env.VILLANI_USE_PI_MODEL='false'; await runVillani('task',{sendMessage:(m:string)=>notes.push(m)},{ui:{notify:(m:string)=>notes.push(m)},cwd:'/tmp',model:{id:'m'},});} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; delete process.env.VILLANI_USE_PI_MODEL;} const joined=notes.join('\n'); assert.match(joined,/Villani bridge ready/); assert.match(joined,/Villani run command sent/); assert.match(joined,/Villani run started\./); assert.ok(notes.indexOf('Villani run command sent.')<notes.indexOf('Villani run started.'));});

test('/villani missing run_started timeout reports visible error instead of started',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping')send({type:'pong'});}}); console.error('no ack'); setTimeout(()=>{},15000);\n"); process.env.VILLANI_COMMAND=p; const notes:string[]=[]; try{process.env.VILLANI_USE_PI_MODEL='false'; await assert.rejects(()=>runVillani('task',{},{ui:{notify:(m:string)=>notes.push(m)},cwd:'/tmp'}),/did not acknowledge run command within 10 seconds.*no ack/s);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; delete process.env.VILLANI_USE_PI_MODEL;} assert.doesNotMatch(notes.join('\n'),/Villani run started\./);});


async function waitForPidGone(pid:number,timeoutMs=3000){const deadline=Date.now()+timeoutMs; while(Date.now()<deadline){try{process.kill(pid,0);}catch{return;} await new Promise(r=>setTimeout(r,50));} assert.fail(`fake bridge process ${pid} remained alive`);}

test('/villani run_started timeout cleans up fake bridge process',async()=>{const oldCommand=process.env.VILLANI_COMMAND; const oldUsePi=process.env.VILLANI_USE_PI_MODEL; const d=mkdtempSync(join(tmpdir(),'pi-villani-cleanup-')); const pidFile=join(d,'pid'); const p=join(d,'bridge.mjs'); writeFileSync(p,`#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
writeFileSync(${JSON.stringify(pidFile)},String(process.pid));
process.stdout.write(JSON.stringify({type:'ready'})+'\\n');
process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping')process.stdout.write(JSON.stringify({type:'pong'})+'\\n');}});
console.error('cleanup no ack');
setInterval(()=>{},1000);
`); chmodSync(p,0o755); process.env.VILLANI_COMMAND=p; process.env.VILLANI_USE_PI_MODEL='false'; const notes:string[]=[]; try{await assert.rejects(()=>runVillani('task',{},{ui:{notify:(m:string)=>notes.push(m)},cwd:'/tmp'}),/did not acknowledge run command within 10 seconds.*cleanup no ack/s); assert.ok(existsSync(pidFile)); await waitForPidGone(Number(readFileSync(pidFile,'utf8'))); assert.doesNotMatch(notes.join('\n'),/Villani run started\./);} finally{if(oldCommand===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=oldCommand; if(oldUsePi===undefined) delete process.env.VILLANI_USE_PI_MODEL; else process.env.VILLANI_USE_PI_MODEL=oldUsePi;}});


test('bridge exit before ready with ModuleNotFoundError produces pip install diagnostic',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript("console.error(\"ModuleNotFoundError: No module named 'villani_code'\"); process.exit(1);\n"); process.env.VILLANI_COMMAND=p; try{await assert.rejects(()=>bridgePing({ui:{notify:()=>{}}}),/pip install -e/);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old;} });

test('/villani-bridge-ping succeeds with fake bridge',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split(/\\n/)){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping')send({type:'pong'});}}); setTimeout(()=>{},500);\n"); process.env.VILLANI_COMMAND=p; const notes:string[]=[]; try{await bridgePing({ui:{notify:(m:string)=>notes.push(m)}});} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old;} assert.match(notes.join('\n'),/Villani bridge ping succeeded/);});

test('/villani-bridge-ping surfaces stderr on failure',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript("console.error('boom stderr'); process.exit(2);\n"); process.env.VILLANI_COMMAND=p; try{await assert.rejects(()=>bridgePing({ui:{notify:()=>{}}}),/boom stderr/);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old;} });

test('/villani surfaces bridge error before run_started without waiting 10 seconds',async()=>{const old=process.env.VILLANI_COMMAND; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping'){send({type:'pong'}); continue;} if(msg.type==='run')send({type:'error',id:msg.id,error:'bad run command'});}}); setTimeout(()=>{},15000);\n"); process.env.VILLANI_COMMAND=p; const notes:string[]=[]; const started=Date.now(); try{process.env.VILLANI_USE_PI_MODEL='false'; await assert.rejects(()=>runVillani('task',{},{ui:{notify:(m:string)=>notes.push(m)},cwd:'/tmp'}),/bad run command/); assert.ok(Date.now()-started<5000);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; delete process.env.VILLANI_USE_PI_MODEL;} assert.doesNotMatch(notes.join('\n'),/Villani run started\./);});

test('/villani launches bridge with ctx cwd',async()=>{const old=process.env.VILLANI_COMMAND; const oldUsePi=process.env.VILLANI_USE_PI_MODEL; const d=mkdtempSync(join(tmpdir(),'pi-villani-cwd-')); const cwdFile=join(d,'cwd.txt'); const p=bridgeScript(readyPrelude+`import { writeFileSync } from 'node:fs'; writeFileSync(${JSON.stringify(cwdFile)}, process.cwd()); process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping'){send({type:'pong'}); continue;} send({type:'run_started',id:msg.id}); send({type:'phase',id:msg.id,name:'x'}); send({type:'run_completed',id:msg.id,summary:'done'});}}); setTimeout(()=>{},500);\n`); process.env.VILLANI_COMMAND=p; process.env.VILLANI_USE_PI_MODEL='false'; try{await runVillani('task',{sendMessage:()=>{}},{ui:{notify:()=>{}},cwd:d,model:{id:'m'}}); assert.equal(readFileSync(cwdFile,'utf8'),d);} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; if(oldUsePi===undefined) delete process.env.VILLANI_USE_PI_MODEL; else process.env.VILLANI_USE_PI_MODEL=oldUsePi;}});

test('VILLANI_PI_DEBUG renders bridge diagnostics visibly',async()=>{const old=process.env.VILLANI_PI_DEBUG; const notes:string[]=[]; try{process.env.VILLANI_PI_DEBUG='1'; const { renderBridgeEvent } = await import('./render.js'); await renderBridgeEvent({type:'bridge_diagnostic',message:'capturing initial git status'},{},{ui:{notify:(m:string)=>notes.push(m)}}); assert.match(notes.join('\n'),/capturing initial git status/);} finally{if(old===undefined) delete process.env.VILLANI_PI_DEBUG; else process.env.VILLANI_PI_DEBUG=old;}});

test('sendDurableVillaniMessage sends a structured iterable custom message',async()=>{const { sendDurableVillaniMessage } = await import('./render.js'); const sent:any[]=[]; await sendDurableVillaniMessage({sendMessage:(m:any)=>sent.push(m)},{ui:{notify:()=>assert.fail('notify should not be used')}} ,'hello',{type:'run_completed',authorization:'Bearer secret',headers:{authorization:'Bearer secret'},apiKey:'secret',token:'secret'}); assert.equal(sent.length,1); assert.notEqual(typeof sent[0],'string'); assert.equal(sent[0].customType,'villani-result'); assert.equal(sent[0].display,true); assert.deepEqual(sent[0].content,[{type:'text',text:'hello'}]); assert.ok(Symbol.iterator in Object(sent[0].content)); assert.doesNotMatch(JSON.stringify(sent[0].details),/secret|authorization|apiKey|token/i);});

test('sendDurableVillaniMessage falls back to ctx.ui.notify if Pi sendMessage throws',async()=>{const { sendDurableVillaniMessage } = await import('./render.js'); const notes:string[]=[]; await sendDurableVillaniMessage({sendMessage:async()=>{throw new Error('boom');}},{ui:{notify:(m:string,level:string)=>notes.push(`${level}:${m}`)}} ,'fallback text'); assert.deepEqual(notes,['info:fallback text']);});

test('renderBridgeEvent does not send durable final messages',async()=>{const { renderBridgeEvent } = await import('./render.js'); let sent=0; const notes:string[]=[]; for(const type of ['run_completed','run_failed','run_aborted']) await renderBridgeEvent({type,summary:'done'},{sendMessage:()=>sent++},{ui:{notify:(m:string)=>notes.push(m)}}); assert.equal(sent,0); assert.deepEqual(notes,[]);});

test('/villani sends exactly one iterable final durable message with summary metadata',async()=>{const old=process.env.VILLANI_COMMAND; const oldUsePi=process.env.VILLANI_USE_PI_MODEL; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping'){send({type:'pong'}); continue;} send({type:'run_started',id:msg.id}); send({type:'model_request_started',id:msg.id}); send({type:'run_completed',id:msg.id,summary:'done',changed_files:['src/a.ts','.villani/secret'],transcript_path:'/tmp/transcript.jsonl',verification_status:'passed',authorization:'Bearer secret',headers:{authorization:'Bearer secret'}});}}); setTimeout(()=>{},500);\n"); const sent:any[]=[]; try{process.env.VILLANI_COMMAND=p; process.env.VILLANI_USE_PI_MODEL='false'; await runVillani('task',{sendMessage:(m:any)=>sent.push(m)},{ui:{notify:()=>{}},cwd:'/tmp',model:{id:'m'}});} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; if(oldUsePi===undefined) delete process.env.VILLANI_USE_PI_MODEL; else process.env.VILLANI_USE_PI_MODEL=oldUsePi;} assert.equal(sent.length,1); const payload=sent[0]; assert.equal(payload.customType,'villani-result'); assert.deepEqual(payload.content,[{type:'text',text:payload.content[0].text}]); assert.ok(Array.isArray(payload.content)); assert.match(payload.content[0].text,/Villani completed/); assert.match(payload.content[0].text,/done/); assert.match(payload.content[0].text,/src\/a\.ts/); assert.doesNotMatch(payload.content[0].text,/\.villani\/secret/); assert.match(payload.content[0].text,/Transcript: \/tmp\/transcript\.jsonl/); assert.match(payload.content[0].text,/Verification: passed/); assert.doesNotMatch(JSON.stringify(payload.details),/authorization|Bearer secret/i);});

test('approvalMessage never renders object and includes Bash command',async()=>{const { approvalMessage, approvalTitle } = await import('./index.js'); const msg=approvalMessage({tool:'Bash',summary:'Run command',input:{command:'echo hi'}}); assert.doesNotMatch(msg,/\[object Object\]/); assert.match(msg,/Command:\necho hi/); assert.equal(approvalTitle({tool:'Bash'}),'Villani wants to run a shell command');});

test('confirm passes signal option to ctx.ui.confirm',async()=>{const { confirm } = await import('./render.js'); const signal=new AbortController().signal; let args:any[]=[]; const ok=await confirm({ui:{confirm:async(...a:any[])=>{args=a; return true;}}},'t','m',{signal}); assert.equal(ok,true); assert.equal(args[2].signal,signal);});

test('/villani approval pending sets status/widget and accepted clears widget',async()=>{const old=process.env.VILLANI_COMMAND; const oldUsePi=process.env.VILLANI_USE_PI_MODEL; const p=bridgeScript(readyPrelude+"process.stdin.on('data',chunk=>{for(const line of chunk.toString().trim().split('\\n')){if(!line)continue; const msg=JSON.parse(line); if(msg.type==='ping'){send({type:'pong'}); continue;} if(msg.type==='approval_response'){send({type:'tool_progress',id:msg.id,tool:'Bash',message:'Running command: echo hi'}); send({type:'run_completed',id:msg.id,summary:'done'}); continue;} send({type:'run_started',id:msg.id}); send({type:'approval_required',id:msg.id,request_id:msg.id+':1',tool:'Bash',summary:'Run command',input:{command:'echo hi'}});}}); setTimeout(()=>{},500);\n"); const statuses:any[]=[]; const widgets:any[]=[]; const confirms:any[]=[]; try{process.env.VILLANI_COMMAND=p; process.env.VILLANI_USE_PI_MODEL='false'; await runVillani('task',{sendMessage:()=>{}},{ui:{notify:()=>{},setStatus:(...a:any[])=>statuses.push(a),setWidget:(...a:any[])=>widgets.push(a),confirm:async(...a:any[])=>{confirms.push(a); return true;}},cwd:'/tmp',model:{id:'m'}});} finally{if(old===undefined) delete process.env.VILLANI_COMMAND; else process.env.VILLANI_COMMAND=old; if(oldUsePi===undefined) delete process.env.VILLANI_USE_PI_MODEL; else process.env.VILLANI_USE_PI_MODEL=oldUsePi;} assert.ok(statuses.some(a=>a[0]==='villani'&&/awaiting approval/.test(a[1]))); assert.ok(widgets.some(a=>a[0]==='villani'&&Array.isArray(a[1]))); assert.ok(widgets.some(a=>a[0]==='villani'&&a[1]===undefined)); assert.equal(confirms[0][2].signal instanceof AbortSignal,true);});

test('tool result and finished events render readable summaries',async()=>{const { renderBridgeEvent } = await import('./render.js'); const notes:string[]=[]; await renderBridgeEvent({type:'tool_finished',tool:'Bash',summary:'Command finished: exit 0',ok:true},{},{ui:{notify:(m:string)=>notes.push(m)}}); await renderBridgeEvent({type:'tool_progress',message:'Running command: echo hi'},{},{ui:{notify:(m:string)=>notes.push(m)}}); assert.match(notes.join('\n'),/Villani tool finished: Bash — Command finished: exit 0/); assert.match(notes.join('\n'),/Villani: Running command: echo hi/);});
