import http from 'node:http';
import * as PiAI from '@earendil-works/pi-ai';
import type { OpenAIMessage, PiCompletionResult } from './protocol.js';
export function zeroUsage(){return {prompt_tokens:0,completion_tokens:0,total_tokens:0};}
function sanitize(e:unknown){return String((e as Error)?.message||e).replace(/Bearer\s+\S+/ig,'Bearer [redacted]').replace(/sk-[A-Za-z0-9_-]+/g,'[redacted]').replace(/(OPENAI_API_KEY|ANTHROPIC_API_KEY|VILLANI_API_KEY)=[^\s]+/ig,'$1=[redacted]');}
export function resolvePiModel(ctx:any):any{ if(process.env.VILLANI_USE_PI_MODEL==='false') return {id:process.env.VILLANI_MODEL||'villani-env-model', bypass:true}; const m=ctx?.model; if(!m) throw new Error('No active Pi model available. Select or launch Pi with a model, then retry.'); return m; }
function toPiMessages(messages:OpenAIMessage[]){return (messages||[]).map(m=>m.role==='tool'?{role:'tool',toolCallId:m.tool_call_id,content:m.content}:m);}
function normCalls(calls:any[]|undefined){return (calls||[]).map(c=>({id:c.id||`call_${Math.random().toString(36).slice(2)}`,type:'function',function:{name:c.name??c.function?.name,arguments:typeof (c.arguments??c.function?.arguments)==='string'?(c.arguments??c.function?.arguments):JSON.stringify(c.arguments??c.function?.arguments??{})}}));}
async function collectIterable(iter:AsyncIterable<any>, signal:AbortSignal):Promise<PiCompletionResult>{let text=''; const tool_calls:any[]=[]; for await(const ev of iter){ if(signal.aborted) throw new Error('aborted'); text+=ev?.textDelta??ev?.delta??ev?.text??ev?.content??''; tool_calls.push(...normCalls(ev?.toolCalls??ev?.tool_calls??(ev?.toolCall?[ev.toolCall]:undefined))); } return {text,tool_calls};}
export async function completeWithPi(model:any, ctx:any, messages:OpenAIMessage[], options:any, signal:AbortSignal):Promise<PiCompletionResult>{
  if(ctx?.modelRegistry?.getApiKeyAndHeaders) await ctx.modelRegistry.getApiKeyAndHeaders(model);
  const context:any={messages:toPiMessages(messages),tools:options?.tools};
  if(model?.api?.streamSimple) return collectIterable(model.api.streamSimple(model, context, {signal, ...options}), signal);
  if(typeof model?.complete==='function'){ const r=await model.complete({messages:context.messages, tools:context.tools, signal, ...options}); return {text:r?.text??r?.content??r?.message?.content??String(r??''), tool_calls:normCalls(r?.toolCalls??r?.tool_calls??r?.message?.tool_calls)}; }
  if(typeof ctx?.pi?.complete==='function'){ const r=await ctx.pi.complete(model,{messages:context.messages,tools:context.tools,signal,...options}); return {text:r?.text??r?.content??r?.message?.content??String(r??''),tool_calls:normCalls(r?.toolCalls??r?.tool_calls??r?.message?.tool_calls)}; }
  const packageComplete = (PiAI as any).complete;
  if(typeof packageComplete==='function'){ const r:any=await packageComplete(model, context, {signal, ...options}); return {text:r?.text??r?.content??r?.message?.content??String(r??''),tool_calls:normCalls(r?.toolCalls??r?.tool_calls??r?.message?.tool_calls)}; }
  throw new Error('Active Pi model cannot be proxied: no supported completion API found.');
}
export async function startModelProxyFromPiModel(model:any, ctx:any={}, signal?:AbortSignal){const ac = signal ?? new AbortController().signal; const server=http.createServer(async(req,res)=>{ if(req.method!=='POST'||(req.url||'').split('?')[0]!=='/v1/chat/completions'){res.writeHead(404).end();return;} let body=''; req.on('data',d=>body+=d); req.on('end',async()=>{try{const j=JSON.parse(body||'{}'); const got=await completeWithPi(model,ctx,j.messages||[],j,ac); const msg:any={role:'assistant',content:got.text}; if(got.tool_calls.length) msg.tool_calls=got.tool_calls; const base:any={id:'pi-villani',created:Math.floor(Date.now()/1000),model:j.model||model.id||'pi-current-model',choices:[{index:0,finish_reason:got.tool_calls.length?'tool_calls':'stop'}]}; if(j.stream){res.writeHead(200,{'content-type':'text/event-stream'}); res.write(`data: ${JSON.stringify({...base,object:'chat.completion.chunk',choices:[{index:0,delta:msg,finish_reason:base.choices[0].finish_reason}]})}\n\n`); res.end('data: [DONE]\n\n');} else {res.writeHead(200,{'content-type':'application/json'}); res.end(JSON.stringify({...base,object:'chat.completion',choices:[{index:0,message:msg,finish_reason:base.choices[0].finish_reason}],usage:zeroUsage()}));}}catch(e){res.writeHead(500,{'content-type':'application/json'}); res.end(JSON.stringify({error:{message:sanitize(e)}}));}});}); if(signal) signal.addEventListener('abort',()=>server.close(),{once:true}); await new Promise<void>(r=>server.listen(0,'127.0.0.1',r)); const addr=server.address(); if(!addr||typeof addr==='string') throw new Error('Proxy bind failed'); return {url:`http://127.0.0.1:${addr.port}`, close:()=>server.close(), address:addr};}
export const startModelProxy=startModelProxyFromPiModel;
