import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtempSync, writeFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { VillaniBridgeProcess, sanitizedEnv } from './process.js';
function script(dir:string, body:string){const p=join(dir,'fake-ready-bridge.mjs'); writeFileSync(p,body); return p;}
const readyBridge="process.stdout.write(JSON.stringify({type:'ready',protocol_version:1})+'\\n');\nprocess.stdin.on('data',chunk=>{for(const line of chunk.toString().split(/\\r?\\n/)){if(!line.trim())continue; const msg=JSON.parse(line); if(msg.type==='ping')process.stdout.write(JSON.stringify({type:'pong',id:msg.id})+'\\n'); if(msg.type==='abort')process.stdout.write(JSON.stringify({type:'run_aborted',id:msg.id})+'\\n'); if(msg.type==='approval_response')process.stdout.write(JSON.stringify({type:'approval_resolved',id:msg.id,request_id:msg.request_id,approved:msg.approved})+'\\n');}}); setTimeout(()=>{},500);\n";
test('VillaniBridgeProcess launches production bridge stdio by default with shell false and paths with spaces work',async()=>{const d=mkdtempSync(join(tmpdir(),'pi space ')); const p=script(d,"if(process.argv[2]!=='bridge'||process.argv[3]!=='--stdio') process.exit(7); process.stdout.write(JSON.stringify({type:'ready'})+'\\n'); setTimeout(()=>{},200);\n"); const b=new VillaniBridgeProcess(process.execPath,{bridgeArgs:[p,'bridge','--stdio']}); await b.waitUntilReady(1000); assert.equal((b.proc as any).spawnfile,process.execPath); assert.equal((b.proc as any).spawnargs[1],p); b.kill(); const prod=new VillaniBridgeProcess(process.execPath); assert.deepEqual(prod.proc.spawnargs.slice(-2),['bridge','--stdio']); assert.equal((prod.proc as any).spawnfile,process.execPath); assert.equal(prod.shell,false); prod.kill();});
test('test bridge args override can use a fixture script',async()=>{const d=mkdtempSync(join(tmpdir(),'pi-')); const p=script(d,readyBridge); const b=new VillaniBridgeProcess(process.execPath,{bridgeArgs:[p]}); await b.waitUntilReady(1000); assert.equal((b.proc as any).spawnargs[1],p); b.kill();});
test('bridge readiness timeout includes stderr',async()=>{const d=mkdtempSync(join(tmpdir(),'pi-')); const p=script(d,"console.error('bad stderr'); setTimeout(()=>{},300);\n"); const b=new VillaniBridgeProcess(process.execPath,{bridgeArgs:[p]}); await assert.rejects(()=>b.waitUntilReady(800),/bad stderr/); b.kill();});
test('malformed JSONL kills process',async()=>{const d=mkdtempSync(join(tmpdir(),'pi-')); const p=script(d,"console.log('nope'); setTimeout(()=>{},500);\n"); const b=new VillaniBridgeProcess(process.execPath,{bridgeArgs:[p]}); await assert.rejects(()=>new Promise((_,rej)=>b.once('error',rej)),/Malformed JSONL/); assert.equal(b.proc.killed,true);});
test('abort and approval response send correct JSONL',async()=>{const d=mkdtempSync(join(tmpdir(),'pi-')); const p=script(d,readyBridge); const b=new VillaniBridgeProcess(process.execPath,{bridgeArgs:[p]}); await b.waitUntilReady(1000); const got:any[]=[]; b.on('event',e=>{if(e.type!=='ready')got.push(e)}); b.abort('r'); b.respondToApproval('r','r:1',true); await new Promise(r=>setTimeout(r,50)); b.kill(); assert.deepEqual(got,[{type:'run_aborted',id:'r'},{type:'approval_resolved',id:'r',request_id:'r:1',approved:true}]);});
test('sanitizes secrets only in proxy mode and explicit config preserves env',()=>{const env:any={OPENAI_API_KEY:'x',ANTHROPIC_API_KEY:'a',VILLANI_API_KEY:'v',CUSTOM_TOKEN:'y',X_AUTH:'z',Y_BEARER:'b',PATH:'p'}; const e=sanitizedEnv({proxyMode:true,env}); assert.equal(e.OPENAI_API_KEY,undefined); assert.equal(e.ANTHROPIC_API_KEY,undefined); assert.equal(e.VILLANI_API_KEY,undefined); assert.equal(e.CUSTOM_TOKEN,undefined); assert.equal(e.X_AUTH,undefined); assert.equal(e.Y_BEARER,undefined); assert.equal(e.PATH,'p'); assert.equal(sanitizedEnv({proxyMode:true,explicitConfigMode:true,env}).VILLANI_API_KEY,'v');});
