import { spawn, ChildProcessWithoutNullStreams } from 'node:child_process'; import { EventEmitter } from 'node:events';
export interface BridgeEvent{type:string;[k:string]:unknown} export interface BridgeProcessOptions{proxyMode?:boolean; explicitConfigMode?:boolean; env?:NodeJS.ProcessEnv; cwd?:string; startupTimeoutMs?:number; bridgeArgs?:string[]} export type LaunchOptions=BridgeProcessOptions;
export function sanitizedEnv(opts:BridgeProcessOptions={}):NodeJS.ProcessEnv{const e={...(opts.env||process.env)}; if(opts.proxyMode&&!opts.explicitConfigMode){for(const k of Object.keys(e)){if(['OPENAI_API_KEY','ANTHROPIC_API_KEY','VILLANI_API_KEY'].includes(k)||/(_API_KEY|AUTH|TOKEN|BEARER)$/i.test(k)) delete e[k];}} return e;}
export class VillaniBridgeProcess extends EventEmitter{proc:ChildProcessWithoutNullStreams; ready=false; stderr=''; buffer=''; startupTimeoutMs:number; readonly shell=false;
 constructor(executable:string, opts:BridgeProcessOptions={}){super(); const args=opts.bridgeArgs??['bridge','--stdio']; this.startupTimeoutMs=opts.startupTimeoutMs??10000; this.proc=spawn(executable,args,{shell:false,env:sanitizedEnv(opts),cwd:opts.cwd}); this.proc.stderr.on('data',d=>{this.stderr=(this.stderr+d.toString()).slice(-8000)}); this.proc.stdout.on('data',d=>this.onout(d.toString())); this.proc.once('error',e=>this.emit('error',e));}
 onout(s:string){this.buffer+=s; let i; while((i=this.buffer.indexOf('\n'))>=0){const line=this.buffer.slice(0,i); this.buffer=this.buffer.slice(i+1); if(!line.trim())continue; try{const e=JSON.parse(line); if(e.type==='ready')this.ready=true; this.emit('event',e);}catch{this.kill(); this.emit('error',new Error('Malformed JSONL from bridge'));}}}
 send(c:unknown){this.proc.stdin.write(JSON.stringify(c)+'\n');} abort(runId:string){this.send({type:'abort',id:runId});} respondToApproval(runId:string,requestId:string,approved:boolean){this.send({type:'approval_response',id:runId,request_id:requestId,approved});} kill(){if(!this.proc.killed)this.proc.kill();}
 waitForEvent(type:string,timeoutMs=1000){return new Promise<BridgeEvent|undefined>(r=>{const t=setTimeout(()=>{this.off('event',on);r(undefined);},timeoutMs); const on=(e:BridgeEvent)=>{if(e.type===type){clearTimeout(t);this.off('event',on);r(e);}}; this.on('event',on);});}
 waitUntilReady(timeoutMs=this.startupTimeoutMs){return new Promise<void>((res,rej)=>{if(this.ready)return res(); const t=setTimeout(()=>rej(new Error(`Bridge readiness timeout. stderr: ${this.stderr}`)),timeoutMs); this.on('event',(e:BridgeEvent)=>{if(e.type==='ready'){clearTimeout(t);res();}}); this.proc.once('exit',()=>{clearTimeout(t);rej(new Error(`Bridge exited before ready. stderr: ${this.stderr}`));});});}
 waitForExit(){return new Promise<number|null>(r=>this.proc.once('exit',r));}}
