import test from 'node:test'; import assert from 'node:assert/strict'; import { resolvePiModel, startModelProxy, zeroUsage } from './modelProxy.js';
import { resolveModelAuth, proxyTest } from './index.js';

test('model resolution uses ctx.model and fails clearly without one',()=>{assert.throws(()=>resolvePiModel({}),/No active Pi model/); assert.equal(resolvePiModel({model:{id:'m'} as any}).id,'m');});
test('resolveModelAuth calls ctx.modelRegistry.getApiKeyAndHeaders(model)',async()=>{const model={id:'m'}; let seen; const auth=await resolveModelAuth({modelRegistry:{getApiKeyAndHeaders:async(m:any)=>(seen=m,{ok:true,apiKey:'k',headers:{h:'v'}})}},model); assert.equal(seen,model); assert.deepEqual(auth,{apiKey:'k',headers:{h:'v'}});});
test('auth failure throws clear sanitized error',async()=>{await assert.rejects(()=>resolveModelAuth({modelRegistry:{getApiKeyAndHeaders:async()=>({ok:false,error:'bad Bearer abc sk-secret OPENAI_API_KEY=abc'})}},{id:'m'}),/Villani could not resolve Pi model authentication: bad Bearer \[redacted\] \[redacted\] OPENAI_API_KEY=\[redacted\]/);});
test('proxy uses PiAI.complete path and passes auth',async()=>{let opts:any; const proxy=await startModelProxy({model:{id:'m',api:{streamSimple:async function*(){throw new Error('not preferred');}}},apiKey:'key',headers:{Authorization:'Bearer secret'},completeFn:(async(_m:any,ctx:any,o:any)=>{opts=o; assert.equal(ctx.systemPrompt,'sys'); assert.deepEqual(ctx.messages[0],{role:'user',content:'hi'}); return {content:'ok',usage:{promptTokens:2,completionTokens:1}};}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({messages:[{role:'system',content:'sys'},{role:'user',content:'hi'}]})}); const j:any=await r.json(); assert.equal(j.choices[0].message.content,'ok'); assert.deepEqual(j.usage,{prompt_tokens:2,completion_tokens:1,total_tokens:3}); assert.equal(opts.apiKey,'key'); assert.deepEqual(opts.headers,{Authorization:'Bearer secret'});}finally{await proxy.close();}});
test('unsupported paths return 404',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:''}) as any}); try{const r=await fetch(proxy.url+'/nope',{method:'POST'}); assert.equal(r.status,404);}finally{await proxy.close();}});
test('OpenAI tool result messages and tools converted into Pi context',async()=>{let seen:any; const proxy=await startModelProxy({model:{id:'m'},completeFn:(async(_m:any,ctx:any)=>{seen=ctx; return {content:'ok'};}) as any}); try{await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({messages:[{role:'assistant',content:'use',tool_calls:[{id:'c1',function:{name:'doit',arguments:'{"x":1}'}}]},{role:'tool',tool_call_id:'c1',content:'result'}],tools:[{type:'function',function:{name:'doit',description:'d',parameters:{type:'object'}}}]})}); assert.deepEqual(seen.messages[0],{role:'assistant',content:'use',toolCalls:[{id:'c1',name:'doit',arguments:{x:1}}]}); assert.deepEqual(seen.messages[1],{role:'toolResult',toolCallId:'c1',content:'result'}); assert.deepEqual(seen.tools[0],{name:'doit',description:'d',inputSchema:{type:'object'}});}finally{await proxy.close();}});
test('Pi AssistantMessage toolCall converts to OpenAI tool_calls',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:[{type:'toolCall',id:'c1',name:'doit',arguments:{x:1}}],stopReason:'toolUse'}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const j:any=await r.json(); assert.equal(j.choices[0].finish_reason,'tool_calls'); assert.equal(j.choices[0].message.tool_calls[0].function.name,'doit'); assert.equal(j.choices[0].message.tool_calls[0].function.arguments,'{"x":1}');}finally{await proxy.close();}});
test('streaming mode emits one SSE chunk plus DONE',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:'hi'}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({stream:true})}); const txt=await r.text(); assert.match(txt,/data: .*hi/); assert.match(txt,/data: \[DONE\]/);}finally{await proxy.close();}});
test('upstream errors are sanitized and credentials are not exposed',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>{throw new Error('failed Bearer abc sk-secret OPENAI_API_KEY=abc Authorization: xyz');}}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const txt=await r.text(); assert.equal(r.status,500); assert.doesNotMatch(txt,/Bearer abc|sk-secret|OPENAI_API_KEY=abc|Authorization: xyz/);}finally{await proxy.close();}});
test('abort signal is passed into Pi complete',async()=>{const ac=new AbortController(); let saw:AbortSignal|undefined; const proxy=await startModelProxy({model:{id:'m'},signal:ac.signal,completeFn:(async(_m:any,_ctx:any,o:any)=>{saw=o.signal; return {content:'ok'};}) as any}); try{await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); assert.equal(saw,ac.signal); assert.deepEqual(zeroUsage(),{prompt_tokens:0,completion_tokens:0,total_tokens:0});}finally{await proxy.close();}});
test('/villani-proxy-test sends real request using mocked complete function and hides credentials',async()=>{const notes:string[]=[]; const model={id:'m'}; await proxyTest({model,modelRegistry:{getApiKeyAndHeaders:async()=>({ok:true,apiKey:'sk-secret',headers:{Authorization:'Bearer abc'}})},ui:{notify:(m:string)=>notes.push(m)}, completeFn:async()=>({content:'READY'})}); assert.match(notes.join('\n'),/Villani proxy test succeeded/); assert.doesNotMatch(notes.join('\n'),/sk-secret|Bearer abc/);});
import { readFileSync } from 'node:fs';

test('modelProxy imports primary @earendil-works/pi-ai complete and not compat',()=>{const src=readFileSync(new URL('../src/modelProxy.ts',import.meta.url),'utf8'); assert.match(src,/from '@earendil-works\/pi-ai';/); assert.doesNotMatch(src,/@earendil-works\/pi-ai\/compat/);});
