import test from 'node:test'; import assert from 'node:assert/strict'; import { resolvePiComplete, resolvePiModel, startModelProxy, zeroUsage, _test } from './modelProxy.js';
import { resolveModelAuth, proxyTest } from './index.js';

test('model resolution uses ctx.model and fails clearly without one',()=>{assert.throws(()=>resolvePiModel({}),/No active Pi model/); assert.equal(resolvePiModel({model:{id:'m'} as any}).id,'m');});
test('resolveModelAuth calls ctx.modelRegistry.getApiKeyAndHeaders(model)',async()=>{const model={id:'m'}; let seen; const auth=await resolveModelAuth({modelRegistry:{getApiKeyAndHeaders:async(m:any)=>(seen=m,{ok:true,apiKey:'k',headers:{h:'v'}})}},model); assert.equal(seen,model); assert.deepEqual(auth,{apiKey:'k',headers:{h:'v'}});});
test('auth failure throws clear sanitized error',async()=>{await assert.rejects(()=>resolveModelAuth({modelRegistry:{getApiKeyAndHeaders:async()=>({ok:false,error:'bad Bearer abc sk-secret OPENAI_API_KEY=abc'})}},{id:'m'}),/Villani could not resolve Pi model authentication: bad Bearer \[redacted\] \[redacted\] OPENAI_API_KEY=\[redacted\]/);});
test('proxy uses resolved complete path and passes auth',async()=>{let opts:any; const proxy=await startModelProxy({model:{id:'m',api:{streamSimple:async function*(){throw new Error('not preferred');}}},apiKey:'key',headers:{Authorization:'Bearer secret'},completeFn:(async(_m:any,ctx:any,o:any)=>{opts=o; assert.equal(ctx.systemPrompt,'sys'); assert.equal(ctx.messages[0].role,'user'); assert.equal(ctx.messages[0].content,'hi'); assert.equal(typeof ctx.messages[0].timestamp,'number'); return {content:'ok',usage:{input:2,output:1,totalTokens:3}};}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({messages:[{role:'system',content:'sys'},{role:'user',content:'hi'}]})}); const j:any=await r.json(); assert.equal(j.choices[0].message.content,'ok'); assert.deepEqual(j.usage,{prompt_tokens:2,completion_tokens:1,total_tokens:3}); assert.equal(opts.apiKey,'key'); assert.deepEqual(opts.headers,{Authorization:'Bearer secret'});}finally{await proxy.close();}});
test('unsupported paths return 404',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:''}) as any}); try{const r=await fetch(proxy.url+'/nope',{method:'POST'}); assert.equal(r.status,404);}finally{await proxy.close();}});
test('OpenAI messages and tools convert into old Pi Context shape',async()=>{let seen:any; const assistantUsage={input:4,output:2,totalTokens:6}; const proxy=await startModelProxy({model:{id:'m'},completeFn:(async(_m:any,ctx:any)=>{seen=ctx; return {content:'ok'};}) as any}); try{await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({messages:[{role:'user',content:'hi'},{role:'assistant',content:'use',model:'gpt-test',usage:assistantUsage,stopReason:'toolUse',tool_calls:[{id:'c1',function:{name:'doit',arguments:'{"x":1}'}}]},{role:'tool',tool_call_id:'c1',name:'doit',content:'result'}],tools:[{type:'function',function:{name:'doit',description:'d',parameters:{type:'object'}}}]})}); assert.equal(seen.messages[0].role,'user'); assert.equal(seen.messages[0].content,'hi'); assert.equal(typeof seen.messages[0].timestamp,'number'); assert.equal(seen.messages[1].role,'assistant'); assert.deepEqual(seen.messages[1].content,[{type:'text',text:'use'},{type:'toolCall',id:'c1',name:'doit',arguments:{x:1}}]); assert.equal(seen.messages[1].api,'openai-completions'); assert.equal(seen.messages[1].provider,'pi'); assert.equal(seen.messages[1].model,'gpt-test'); assert.deepEqual(seen.messages[1].usage,zeroUsage()); assert.equal(seen.messages[1].stopReason,'toolUse'); assert.equal(typeof seen.messages[1].timestamp,'number'); assert.deepEqual(seen.messages[2].content,[{type:'text',text:'result'}]); assert.equal(seen.messages[2].role,'toolResult'); assert.equal(seen.messages[2].toolCallId,'c1'); assert.equal(seen.messages[2].toolName,'doit'); assert.equal(seen.messages[2].isError,false); assert.equal(typeof seen.messages[2].timestamp,'number'); assert.deepEqual(seen.tools[0],{name:'doit',description:'d',parameters:{type:'object'}}); assert.equal('toolCalls' in seen.messages[1],false); assert.equal('inputSchema' in seen.tools[0],false);}finally{await proxy.close();}});
test('Pi AssistantMessage toolCall converts to OpenAI tool_calls',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:[{type:'toolCall',id:'c1',name:'doit',arguments:{x:1}}],stopReason:'toolUse'}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const j:any=await r.json(); assert.equal(j.choices[0].finish_reason,'tool_calls'); assert.equal(j.choices[0].message.tool_calls[0].function.name,'doit'); assert.equal(j.choices[0].message.tool_calls[0].function.arguments,'{"x":1}');}finally{await proxy.close();}});

test('Pi finish reasons map to OpenAI values',async()=>{for(const [stopReason,toolCalls,expected] of [['toolUse',true,'tool_calls'],['length',false,'length'],['stop',false,'stop'],[undefined,true,'stop'],[undefined,false,'stop']] as const){const content=toolCalls?[{type:'toolCall',id:'c1',name:'doit',arguments:{}}]:'ok'; const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content,stopReason}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const j:any=await r.json(); assert.equal(j.choices[0].finish_reason,expected); assert.notEqual(j.choices[0].finish_reason,'toolUse');}finally{await proxy.close();}}});


test('non-streaming proxy response exactly matches Pi AssistantMessage conversion shape',async()=>{const assistant:any={content:[{type:'text',text:'hello'},{type:'text',text:'world'}],timestamp:1700000000000,responseId:'resp_1',responseModel:'pi-response-model',model:'pi-model',usage:{input:2,output:3,totalTokens:5},stopReason:'stop'}; const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>assistant}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const j:any=await r.json(); assert.deepEqual(j,_test.piAssistantToOpenAIResponse(assistant) as any); assert.equal(j.choices[0].message.content,'hello\n\nworld');}finally{await proxy.close();}});

test('streaming proxy response preserves old OpenAI chunk shape',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:[{type:'text',text:'hello'}],timestamp:1700000000000,model:'m',usage:{input:1,output:1,totalTokens:2},stopReason:'stop'}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({stream:true})}); const txt=await r.text(); const chunk=JSON.parse(txt.split('\n').find((line)=>line.startsWith('data: {'))!.slice('data: '.length)); assert.equal(chunk.object,'chat.completion.chunk'); assert.equal(chunk.choices[0].delta.role,'assistant'); assert.equal(typeof chunk.choices[0].delta.content,'string'); assert.ok(['stop','length','tool_calls'].includes(chunk.choices[0].finish_reason)); assert.deepEqual(chunk.usage,{prompt_tokens:1,completion_tokens:1,total_tokens:2}); assert.match(txt,/data: \[DONE\]/);}finally{await proxy.close();}});

test('response conversion does not expose simplified assistantFromPi path',()=>{assert.equal('assistantFromPi' in _test,false);});

test('streaming mode emits one SSE chunk plus DONE',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:'hi'}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({stream:true})}); const txt=await r.text(); assert.match(txt,/data: .*hi/); assert.match(txt,/data: \[DONE\]/);}finally{await proxy.close();}});

test('Pi stopReason error and aborted become upstream errors',async()=>{for(const stopReason of ['error','aborted']){const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:[{type:'text',text:'bad'}],stopReason}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const j:any=await r.json(); assert.equal(r.status,500); assert.equal(j.error.type,'upstream_error'); assert.match(j.error.message,stopReason==='aborted'?/aborted/:/Pi model request failed/);}finally{await proxy.close();}}});
test('upstream errors are sanitized and credentials are not exposed',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>{throw new Error('failed Bearer abc sk-secret OPENAI_API_KEY=abc Authorization: xyz');}}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const txt=await r.text(); assert.equal(r.status,500); assert.doesNotMatch(txt,/Bearer abc|sk-secret|OPENAI_API_KEY=abc|Authorization: xyz/);}finally{await proxy.close();}});
test('abort signal is passed into Pi complete',async()=>{const ac=new AbortController(); let saw:AbortSignal|undefined; const proxy=await startModelProxy({model:{id:'m'},signal:ac.signal,completeFn:(async(_m:any,_ctx:any,o:any)=>{saw=o.signal; return {content:'ok'};}) as any}); try{await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); assert.equal(saw,ac.signal); assert.deepEqual(zeroUsage(),{input:0,output:0,totalTokens:0});}finally{await proxy.close();}});
test('/villani-proxy-test sends real request using mocked complete function, reports selected helper, and hides credentials',async()=>{const notes:string[]=[]; const model={id:'m'}; await proxyTest({model,modelRegistry:{getApiKeyAndHeaders:async()=>({ok:true,apiKey:'sk-secret',headers:{Authorization:'Bearer abc'}})},ui:{notify:(m:string)=>notes.push(m)}, completeFn:async()=>({content:'READY'}),completeSource:'test:complete'}); const msg=notes.join('\n'); assert.match(msg,/Villani proxy test succeeded/); assert.match(msg,/selected Pi completion helper source: test:complete/); assert.match(msg,/active model id: m/); assert.match(msg,/auth resolution succeeded: true/); assert.doesNotMatch(msg,/sk-secret|Bearer abc/);});

test('resolvePiComplete finds top-level complete',async()=>{const fn=()=>{}; const r=await resolvePiComplete(async()=>({complete:fn})); assert.equal(r.fn,fn); assert.equal(r.source,'@earendil-works/pi-ai:complete');});
test('resolvePiComplete finds default.complete',async()=>{const fn=()=>{}; const r=await resolvePiComplete(async()=>({default:{complete:fn}})); assert.equal(r.fn,fn); assert.equal(r.source,'@earendil-works/pi-ai:default.complete');});
test('resolvePiComplete finds compat.complete',async()=>{const fn=()=>{}; const r=await resolvePiComplete(async()=>({compat:{complete:fn}})); assert.equal(r.fn,fn); assert.equal(r.source,'@earendil-works/pi-ai:compat.complete');});
test('resolvePiComplete tries compat package if primary lacks complete',async()=>{const fn=()=>{}; const seen:string[]=[]; const r=await resolvePiComplete(async(name)=>{seen.push(name); return name.endsWith('/compat')?{complete:fn}:{};}); assert.deepEqual(seen,['@earendil-works/pi-ai','@earendil-works/pi-ai/compat']); assert.equal(r.source,'@earendil-works/pi-ai/compat:complete');});
test('no compatible helper produces a clear visible error',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeImporter:async()=>({})}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:'{}'}); const txt=await r.text(); assert.equal(r.status,500); assert.match(txt,/Active Pi model cannot be proxied: no supported completion API found/); assert.doesNotMatch(txt,/PiAI\.complete is unavailable/);}finally{await proxy.close();}});

test('toOpenAIToolCalls converts object arguments to JSON object string',()=>{const calls=(_test as any).toOpenAIToolCalls([{type:'toolCall',id:'c1',name:'doit',arguments:{x:1}}]); assert.equal(calls[0].function.arguments,'{"x":1}');});

test('toOpenAIToolCalls converts JSON string object arguments to JSON object string',()=>{const calls=(_test as any).toOpenAIToolCalls([{type:'toolCall',id:'c1',name:'doit',arguments:'{"path":"x"}'}]); assert.equal(calls[0].function.arguments,'{"path":"x"}');});

test('toOpenAIToolCalls converts invalid string arguments to empty object string',()=>{const calls=(_test as any).toOpenAIToolCalls([{type:'toolCall',id:'c1',name:'doit',arguments:'repo'}]); assert.equal(calls[0].function.arguments,'{}');});

test('toOpenAIToolCalls converts array string and number arguments to empty object string',()=>{for(const value of [[1], '"repo"', 42]){const calls=(_test as any).toOpenAIToolCalls([{type:'toolCall',id:'c1',name:'doit',arguments:value}]); assert.equal(calls[0].function.arguments,'{}');}});

test('streaming tool call response never emits raw non-object arguments',async()=>{const proxy=await startModelProxy({model:{id:'m'},completeFn:async()=>({content:[{type:'toolCall',id:'c1',name:'doit',arguments:'repo'}],stopReason:'toolUse'}) as any}); try{const r=await fetch(proxy.url+'/v1/chat/completions',{method:'POST',body:JSON.stringify({stream:true})}); const txt=await r.text(); assert.doesNotMatch(txt,/"arguments":"repo"/); assert.match(txt,/"arguments":"\{\}"/);}finally{await proxy.close();}});

test('proxy text response conversion remains unchanged',()=>{const assistant:any={content:[{type:'text',text:'hello'},{type:'text',text:'world'}],timestamp:1700000000000,responseId:'resp_1',responseModel:'pi-response-model',usage:{input:2,output:3,totalTokens:5},stopReason:'stop'}; const converted:any=_test.piAssistantToOpenAIResponse(assistant); assert.equal(converted.choices[0].message.content,'hello\n\nworld'); assert.equal(converted.choices[0].message.tool_calls,undefined); assert.deepEqual(converted.usage,{prompt_tokens:2,completion_tokens:3,total_tokens:5});});
