import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import AdmZip from 'adm-zip';
import * as tar from 'tar';
import { assetName, executableRelativePath, platformKey, VILLANI_RUNTIME_REPOSITORY, VILLANI_RUNTIME_TAG, VILLANI_RUNTIME_VERSION } from './runtimeConfig.js';
export function parseChecksums(text:string): Map<string,string>{const m=new Map<string,string>(); for(const l of text.split(/\r?\n/)){const p=l.trim().split(/\s+/); if(p.length>=2)m.set(p[p.length-1],p[0]);} return m;}
export function cacheRoot(){return process.platform==='win32'?join(process.env.LOCALAPPDATA||homedir(),'pi-villani','runtime'):join(homedir(),'.cache','pi-villani','runtime');}
async function download(url:string, signal?:AbortSignal):Promise<Buffer>{const r=await fetch(url,{signal}); if(!r.ok) throw new Error(`Download failed ${r.status}: ${url}`); return Buffer.from(await r.arrayBuffer());}
export async function extractRuntimeArchive(archive:string,dest:string):Promise<void>{mkdirSync(dest,{recursive:true}); if(archive.endsWith('.zip')){new AdmZip(archive).extractAllTo(dest,true); return;} await tar.x({file:archive,cwd:dest,gzip:true});}
export async function resolveVillaniRuntime(opts:{signal?:AbortSignal, platform?:string, arch?:string}={}):Promise<string>{ if(process.env.VILLANI_COMMAND) return process.env.VILLANI_COMMAND; const key=platformKey(opts.platform as any, opts.arch as any); const asset=assetName(key); const root=cacheRoot(); const dest=join(root,VILLANI_RUNTIME_VERSION); const exe=join(dest,executableRelativePath(key)); const marker=join(dest,'.verified.json'); const base=`https://github.com/${VILLANI_RUNTIME_REPOSITORY}/releases/download/${VILLANI_RUNTIME_TAG}`; const checks=parseChecksums((await download(`${base}/checksums.txt`,opts.signal)).toString('utf8')); const sum=checks.get(asset); if(!sum) throw new Error(`Missing checksum for ${asset}`); if(existsSync(exe)&&existsSync(marker)){try{const j=JSON.parse(readFileSync(marker,'utf8')); if(j.version===VILLANI_RUNTIME_VERSION&&j.asset===asset&&j.sha256===sum)return exe;}catch{}}
 const buf=await download(`${base}/${asset}`,opts.signal); const got=createHash('sha256').update(buf).digest('hex'); if(got!==sum) throw new Error(`Checksum mismatch for ${asset}`); mkdirSync(dest,{recursive:true}); const archive=join(dest,asset); writeFileSync(archive,buf); await extractRuntimeArchive(archive,dest); if(!existsSync(exe)) throw new Error(`Runtime executable missing after extraction: ${exe}`); writeFileSync(marker,JSON.stringify({version:VILLANI_RUNTIME_VERSION,asset,sha256:sum})); return exe; }
